import { Company, Region, ServiceItem } from '../types';

export const REGIONS: Region[] = [
  { name: 'Stadt Luzern', slug: 'luzern', zip: '6000' },
  { name: 'Emmen & Rothenburg', slug: 'emmen', zip: '6020' },
  { name: 'Kriens', slug: 'kriens', zip: '6010' },
  { name: 'Horw', slug: 'horw', zip: '6048' },
  { name: 'Sursee & Sempachersee', slug: 'sursee', zip: '6210' },
  { name: 'Willisau & Wiggertal', slug: 'willisau', zip: '6130' },
  { name: 'Seetal & Hochdorf', slug: 'seetal', zip: '6280' },
  { name: 'Rontal & Ebikon', slug: 'rontal', zip: '6030' },
  { name: 'Nidwalden', slug: 'nidwalden', zip: '6370' },
  { name: 'Obwalden', slug: 'obwalden', zip: '6060' },
  { name: 'Schwyz', slug: 'schwyz', zip: '6430' },
  { name: 'Uri', slug: 'uri', zip: '6460' },
  { name: 'Entlebuch', slug: 'entlebuch', zip: '6162' },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'installation',
    title: 'Elektroinstallation',
    slug: 'elektroinstallation',
    icon: 'PlugZap',
    shortDesc: 'Fachgerechte Installation für Neu- und Umbauten.',
    fullDesc: 'Wir bieten umfassende Elektroinstallationen für Neubauten, Renovierungen und industrielle Anlagen. Von der Planung der Steckdosen bis zum komplexen Sicherungskasten garantieren wir höchste Sicherheitsstandards.',
    metaTitle: 'Elektroinstallation Luzern | Neu- & Umbau Profis',
    metaDesc: 'Zertifizierte Elektroinstallationen in Luzern. Sicherungskästen, Leitungsverlegung und Anschlüsse für Küche & Bad. Jetzt Offerte anfordern.',
  },
  {
    id: 'wartung',
    title: 'Wartung & Reparatur',
    slug: 'wartung-reparatur',
    icon: 'Wrench',
    shortDesc: 'Schnelle Fehlersuche und zuverlässige Reparaturen.',
    fullDesc: 'Elektrische Probleme können gefährlich sein. Unsere Experten sind spezialisiert auf schnelle Fehlersuche, Reparatur von Defekten und regelmässige Wartung Ihrer elektrischen Anlagen, um Ausfälle zu vermeiden.',
    metaTitle: 'Elektriker Reparaturservice Luzern | 24h Notdienst',
    metaDesc: 'Schnelle Hilfe bei Stromausfall und Defekten in Luzern. Professionelle Fehlersuche und Reparatur durch geprüfte Fachbetriebe.',
  },
  {
    id: 'smarthome',
    title: 'Smart Home & Netzwerk',
    slug: 'smart-home',
    icon: 'Wifi',
    shortDesc: 'Intelligente Gebäudesteuerung und stabiles WLAN.',
    fullDesc: 'Machen Sie Ihr Zuhause intelligent. Wir planen und installieren KNX, Loxone und andere Smart-Home-Systeme. Zudem sorgen wir für eine strukturierte Netzwerkverkabelung und perfektes WLAN im ganzen Haus.',
    metaTitle: 'Smart Home Installation Luzern | KNX & Loxone Partner',
    metaDesc: 'Ihr Experte für Smart Home in Luzern. Automatisierung, Netzwerktechnik und Sicherheitssysteme professionell installiert.',
  },
  {
    id: 'solar',
    title: 'Erneuerbare Energien',
    slug: 'erneuerbare-energien',
    icon: 'Sun',
    shortDesc: 'PV-Anlagen, Batteriespeicher und Wallboxen.',
    fullDesc: 'Setzen Sie auf die Zukunft. Wir schliessen Ihre Photovoltaikanlage an, installieren Batteriespeicher für maximale Unabhängigkeit und montieren Wallboxen für Ihr Elektrofahrzeug.',
    metaTitle: 'Wallbox & PV-Anlagen Installation Luzern',
    metaDesc: 'Fachbetrieb für E-Mobilität und Solartechnik in Luzern. Wallbox-Installation, PV-Anschluss und Batteriespeicher aus einer Hand.',
  },
  {
    id: 'sicherheit',
    title: 'Sicherheitsprüfungen',
    slug: 'sicherheitspruefung',
    icon: 'ShieldCheck',
    shortDesc: 'SiNa Sicherheitsnachweis und E-Check.',
    fullDesc: 'Sicherheit geht vor. Als zertifizierte Kontrolleure führen wir den gesetzlich vorgeschriebenen Sicherheitsnachweis (SiNa) durch und überprüfen Ihre Installationen auf Normkonformität (NIV).',
    metaTitle: 'SiNa Sicherheitsnachweis Luzern | Elektrokontrolle',
    metaDesc: 'Offizieller Sicherheitsnachweis (SiNa) und Elektro-Check in Luzern. Periodische Kontrollen und Abnahmemessungen günstig buchen.',
  },
  {
    id: 'beleuchtung',
    title: 'Beleuchtungstechnik',
    slug: 'beleuchtung',
    icon: 'Lightbulb',
    shortDesc: 'Moderne LED-Konzepte für Innen und Aussen.',
    fullDesc: 'Das richtige Licht schafft Atmosphäre. Wir planen und installieren energiesparende LED-Beleuchtungskonzepte für Wohnräume, Büros und Aussenanlagen. Inklusive Bewegungsmeldern und Dimmersystemen.',
    metaTitle: 'Lichtplanung & LED Installation Luzern',
    metaDesc: 'Professionelle Beleuchtungstechnik in Luzern. LED-Umrüstung, Gartenbeleuchtung und intelligente Lichtsteuerung.',
  }
];

export const COMPANIES: Company[] = [
    { id: 'c10576', name: '3A Elektro AG', address: 'Luzernerstrasse 35', zip: '6144', city: 'Zell', email: 'info@3a-elektro.ch', location: 'Zell', region: 'willisau', slug: '3a-elektro-ag' },
    { id: 'c10577', name: 'A. Schmidiger AG', address: 'Rüeggisingerstrasse 43', zip: '6020', city: 'Emmenbrücke', email: 'a.schmidiger@schmidiger-elektro.ch', location: 'Emmenbrücke', region: 'emmen', slug: 'a-schmidiger-ag' },
    { id: 'c10578', name: 'AC/DC Solar + Elektro GmbH', address: 'Chilematte 10', zip: '6025', city: 'Neudorf', email: 'info@solarundelektro.ch', location: 'Neudorf', region: 'sursee', slug: 'ac-dc-solar-elektro-gmbh' },
    { id: 'c10579a', name: 'AG Elektro AGZ', address: 'Bahnhofstrasse 41', zip: '6460', city: 'Altdorf UR', email: 'mail@elektroagz.ch', location: 'Altdorf UR', region: 'uri', slug: 'ag-elektro-agz' },
    { id: 'c10579b', name: 'Allenbach Gebr. AG', address: 'Pfrundhofweg 5', zip: '6274', city: 'Eschenbach / LU', email: 'info@allenbach.com', location: 'Eschenbach / LU', region: 'seetal', slug: 'allenbach-gebr-ag' },
    { id: 'c10579c', name: 'Amoled Elektro AG', address: 'Kantonsstrasse 13', zip: '6033', city: 'Buchrain', email: 'info@amoled.ch', location: 'Buchrain', region: 'rontal', slug: 'amoled-elektro-ag' },
    { id: 'c10579d', name: 'Amstein + Walthert Luzern AG', address: 'Allmendstrasse 18', zip: '6048', city: 'Horw', email: 'infolu@amstein-walthert.ch', location: 'Horw', region: 'horw', slug: 'amstein-walthert-luzern-ag' },
    { id: 'c10579e', name: 'AMSTROM AG', address: 'Ried Ost 2', zip: '6074', city: 'Giswil', email: 'mail@amstrom.ch', location: 'Giswil', region: 'obwalden', slug: 'amstrom-ag' },
    { id: 'c10579f', name: 'Aregger Elektro AG', address: 'Grisigenstrasse 12', zip: '6048', city: 'Horw', email: 'horw@aregger-elektro.ch', location: 'Horw', region: 'horw', slug: 'aregger-elektro-ag' },
    { id: 'c10579g', name: 'as-energie GmbH', address: 'Marktstrasse 7a', zip: '6060', city: 'Sarnen', email: 'info@asenergie.ch', location: 'Sarnen', region: 'obwalden', slug: 'as-energie-gmbh' },
    { id: 'c10579h', name: 'ASP Konzept AG', address: 'Spinnereistrasse 7', zip: '6020', city: 'Emmenbrücke', email: 'andreas.spoerli@aspkonzept.ch', location: 'Emmenbrücke', region: 'emmen', slug: 'asp-konzept-ag' },
    { id: 'c10579i', name: 'bähler-wbi ag', address: 'Poststrasse 1', zip: '6403', city: 'Küssnacht am Rigi', email: 'info@baehler-wbi.ch', location: 'Küssnacht am Rigi', region: 'schwyz', slug: 'baehler-wbi-ag' },
    { id: 'c10579j', name: 'Belevo AG', address: 'Lihrenmoos 1', zip: '6122', city: 'Menznau', email: 'info@belevo.ch', location: 'Menznau', region: 'willisau', slug: 'belevo-ag' },
    { id: 'c10579k', name: 'Betschart AG Holz + Elektro', address: 'Hauptstrasse 103', zip: '6436', city: 'Muotathal', email: 'elektro@bhe-ag.ch', location: 'Muotathal', region: 'schwyz', slug: 'betschart-ag-holz-elektro' },
    { id: 'c10579l', name: 'Beutler AG Elektrische Anlagen', address: 'Parkstrasse 19', zip: '6410', city: 'Goldau/SZ', email: 'info@beutler-elektro.ch', location: 'Goldau/SZ', region: 'schwyz', slug: 'beutler-ag-elektrische-anlagen' },
    { id: 'c10579m', name: 'Bonetti Elektro AG', address: 'Kreuzbuchstrasse 77', zip: '6045', city: 'Meggen', email: 'info@bonetti-elektro.ch', location: 'Meggen', region: 'rontal', slug: 'bonetti-elektro-ag' },
    { id: 'c10579n', name: 'Brissoni AG', address: 'Friedentalstrasse 41a', zip: '6004', city: 'Luzern', email: 'mail@elektro-brissoni.ch', location: 'Luzern', region: 'luzern', slug: 'brissoni-ag' },
    { id: 'c10579o', name: 'Brunner Elektroplan AG', address: 'Gibraltarstrasse 34', zip: '6003', city: 'Luzern', email: 'info@el-ing.ch', location: 'Luzern', region: 'luzern', slug: 'brunner-elektroplan-ag' },
    { id: 'c10579p', name: 'Bühlmann Elektroingenieure AG', address: 'Weitblick 1', zip: '6038', city: 'Gisikon', email: 'info@b-ei.ch', location: 'Gisikon', region: 'rontal', slug: 'buehlmann-elektroingenieure-ag' },
    { id: 'c10579q', name: 'Bütler Elektro AG', address: 'Huobenfangstrasse 2', zip: '6023', city: 'Rothenburg', email: 'info@buetler-ag.ch', location: 'Rothenburg', region: 'emmen', slug: 'buetler-elektro-ag' },
    { id: 'c10580a', name: 'Capasso Elektro GmbH', address: 'Grossmatte 30', zip: '6014', city: 'Luzern', email: 'elektro@capasso.ch', location: 'Luzern', region: 'luzern', slug: 'capasso-elektro-gmbh' },
    { id: 'c10580b', name: 'Ch. Bieri Elektro GmbH', address: 'Industrie Nord 12', zip: '6105', city: 'Schachen LU', email: 'info@bieri-elektro.ch', location: 'Schachen LU', region: 'luzern', slug: 'ch-bieri-elektro-gmbh' },
    { id: 'c10580c', name: 'Ch. Furrer Elektro GmbH', address: 'Menzikerstrasse 25a', zip: '6221', city: 'Rickenbach', email: 'info@ch-furrer.ch', location: 'Rickenbach', region: 'sursee', slug: 'ch-furrer-elektro-gmbh' },
    { id: 'c10580d', name: 'cimenti lipp ag luzern', address: 'Emanuel-Müllerstrasse 14', zip: '6010', city: 'Kriens', email: 'info@cimentilipp.ch', location: 'Kriens', region: 'kriens', slug: 'cimenti-lipp-ag-luzern' },
    { id: 'c10580e', name: 'CKW Gebäudetechnik AG', address: 'Täschmattstrasse 4', zip: '6015', city: 'Luzern', email: 'info@ckw.ch', location: 'Luzern', region: 'luzern', slug: 'ckw-gebaeudetechnik-ag' },
    { id: 'c10581a', name: 'Daniel Pfenninger AG', address: 'Giselistrasse 13/15', zip: '6006', city: 'Luzern', email: 'info@elektro-pfenninger.ch', location: 'Luzern', region: 'luzern', slug: 'daniel-pfenninger-ag' },
    { id: 'c10581b', name: 'Dubach Elektro GmbH', address: 'Postfach 65', zip: '6142', city: 'Gettnau / LU', email: 'info@elektro-dubach.ch', location: 'Gettnau / LU', region: 'willisau', slug: 'dubach-elektro-gmbh' },
    { id: 'c10581c', name: 'Durrer Jost Energie GmbH', address: 'Flüelistrasse 26', zip: '6064', city: 'Kerns', email: 'info@durrerenergie.ch', location: 'Kerns', region: 'obwalden', slug: 'durrer-jost-energie-gmbh' },
    { id: 'c10582a', name: 'ebs Energie AG', address: 'Riedstrasse 17', zip: '6431', city: 'Schwyz', email: 'info@ebs.swiss', location: 'Schwyz', region: 'schwyz', slug: 'ebs-energie-ag' },
    { id: 'c10582b', name: 'Edelweiss Elektro AG', address: 'Entlebucherstrasse 78a', zip: '6110', city: 'Wolhusen', email: 'info@edelweiss-elektro.ch', location: 'Wolhusen', region: 'sursee', slug: 'edelweiss-elektro-ag' },
    { id: 'c10582c', name: 'EHB Elektro GmbH', address: 'Rüdel 4', zip: '6122', city: 'Menznau', email: 'info@ehb-elektro.ch', location: 'Menznau', region: 'willisau', slug: 'ehb-elektro-gmbh' },
    { id: 'c10582d', name: 'Ehrenberg Elektro AG', address: 'Maihofstrasse 62a', zip: '6006', city: 'Luzern', email: 'elektro@ehrenberg.ch', location: 'Luzern', region: 'luzern', slug: 'ehrenberg-elektro-ag' },
    { id: 'c10582e', name: 'Electra AG Luzern', address: 'Stubenhalde 4', zip: '6043', city: 'Adligenswil', email: 'odermatt@electra-luzern.ch', location: 'Adligenswil', region: 'rontal', slug: 'electra-ag-luzern' },
    { id: 'c10582f', name: 'Electrocasa AG', address: 'Flurhofstrasse 15', zip: '6374', city: 'Buochs', email: 'pfuis@electrocasa.ch', location: 'Buochs', region: 'nidwalden', slug: 'electrocasa-ag' },
    { id: 'c10582g', name: 'electrotime Wechsler + Bucher AG', address: 'Gartenweg 6', zip: '6232', city: 'Geuensee', email: 'info@electrotime.ch', location: 'Geuensee', region: 'sursee', slug: 'electrotime-wechsler-bucher-ag' },
    { id: 'c10582h', name: 'Elektrizitätswerk Schwyz AG', address: 'Gotthardstrasse 6', zip: '6438', city: 'Ibach', email: 'info@ews.ch', location: 'Ibach', region: 'schwyz', slug: 'elektrizitaetswerk-schwyz-ag' },
    { id: 'c10582i', name: 'Elektrizitätswerk Ursern', address: 'Gotthardstrasse 74', zip: '6490', city: 'Andermatt/UR', email: 'info@ew-ursern.ch', location: 'Andermatt/UR', region: 'uri', slug: 'elektrizitaetswerk-ursern' },
    { id: 'c10582j', name: 'Elektrokonstrukt AG', address: 'Littauerboden 1', zip: '6014', city: 'Luzern', email: 'info@elektrokonstrukt.ch', location: 'Luzern', region: 'luzern', slug: 'elektrokonstrukt-ag' },
    { id: 'c10582k', name: 'Elektro A. Müller AG', address: 'Kantonsstrasse 60', zip: '6048', city: 'Horw', email: 'info@mueller-horw.ch', location: 'Horw', region: 'horw', slug: 'elektro-a-mueller-ag' },
    { id: 'c10582l', name: 'Elektro Baumann GmbH', address: 'Lippenrüti 1', zip: '6206', city: 'Neuenkirch', email: 'info@elektro-baumann.ch', location: 'Neuenkirch', region: 'sursee', slug: 'elektro-baumann-gmbh' },
    { id: 'c10582m', name: 'Elektro Burkart AG', address: 'Dubemoos 2', zip: '6026', city: 'Rain / LU', email: 'strom@elektroburkart.ch', location: 'Rain / LU', region: 'sursee', slug: 'elektro-burkart-ag' },
    { id: 'c10582n', name: 'Elektro Burri Partner AG', address: 'Mettenwilstrasse 14', zip: '6203', city: 'Sempach Station', email: 'mail@ihr-elektropartner.ch', location: 'Sempach Station', region: 'sursee', slug: 'elektro-burri-partner-ag' },
    { id: 'c10582o', name: 'Elektro Egli Späni AG', address: 'Baselstrasse 38', zip: '6003', city: 'Luzern', email: 'info@ees-ag.ch', location: 'Luzern', region: 'luzern', slug: 'elektro-egli-spaeni-ag' },
    { id: 'c10582p', name: 'Elektro Emmenegger GmbH', address: 'Menznauerstrasse 28', zip: '6130', city: 'Willisau', email: 'elektroemmenegger@bluewin.ch', location: 'Willisau', region: 'willisau', slug: 'elektro-emmenegger-gmbh' },
    { id: 'c10582q', name: 'Elektro Engineering Partner AG', address: 'Gerliswilstrasse 8', zip: '6020', city: 'Emmenbrücke', email: 'info@eep.ag', location: 'Emmenbrücke', region: 'emmen', slug: 'elektro-engineering-partner-ag' },
    { id: 'c10582r', name: 'Elektro Ettlin AG', address: 'Sagenstrasse 1', zip: '6064', city: 'Kerns', email: 'elektro.ettlinag@bluewin.ch', location: 'Kerns', region: 'obwalden', slug: 'elektro-ettlin-ag' },
    { id: 'c10582s', name: 'Elektro Felber AG', address: 'Mühlerain 28', zip: '6010', city: 'Kriens', email: 'elektro.felberag@bluewin.ch', location: 'Kriens', region: 'kriens', slug: 'elektro-felber-ag' },
    { id: 'c10583a', name: 'Elektro Fries GmbH', address: 'Dammstrasse 2', zip: '6383', city: 'Dallenwil', email: 'info@elektrofries.ch', location: 'Dallenwil', region: 'nidwalden', slug: 'elektro-fries-gmbh' },
    { id: 'c10583b', name: 'Elektro Fuchs Littau GmbH', address: 'Grubenstrasse 11', zip: '6014', city: 'Luzern', email: 'info@elektrofuchs.ch', location: 'Luzern', region: 'luzern', slug: 'elektro-fuchs-littau-gmbh' },
    { id: 'c10583c', name: 'Elektro Furrer AG', address: 'Edisriederstrasse 83', zip: '6072', city: 'Sachseln', email: 'info@elektrofurrer.ch', location: 'Sachseln', region: 'obwalden', slug: 'elektro-furrer-ag' },
    { id: 'c10583d', name: 'Elektro Gander AG', address: 'Dorfstrasse 21', zip: '6154', city: 'Hofstatt', email: 'info@elektro-gander.ch', location: 'Hofstatt', region: 'willisau', slug: 'elektro-gander-ag' },
    { id: 'c10583e', name: 'Elektro-Getzmann AG', address: 'Luzernerstrasse 6', zip: '6146', city: 'Grossdietwil', email: 'info@elektro-getzmann.ch', location: 'Grossdietwil', region: 'willisau', slug: 'elektro-getzmann-ag' },
    { id: 'c10583f', name: 'Elektro Häberli AG', address: 'Luzernerstrasse 11', zip: '6252', city: 'Dagmersellen', email: 'info@elektro-haeberli.ch', location: 'Dagmersellen', region: 'willisau', slug: 'elektro-haeberli-ag' },
    { id: 'c10583g', name: 'Elektro Hodel AG', address: 'Dorfmatt 10', zip: '6243', city: 'Egolzwil', email: 'info@elektrohodel.ch', location: 'Egolzwil', region: 'willisau', slug: 'elektro-hodel-ag' },
    { id: 'c10583h', name: 'Elektro Hof', address: 'Kirchenweg 14', zip: '6103', city: 'Schwarzenberg LU', email: 'elektrohof@bluewin.ch', location: 'Schwarzenberg LU', region: 'luzern', slug: 'elektro-hof' },
    { id: 'c10583i', name: 'Elektro Horat AG', address: 'Gotthardstrasse 202', zip: '6423', city: 'Seewen', email: 'info@elektro-horat.ch', location: 'Seewen', region: 'schwyz', slug: 'elektro-horat-ag' },
    { id: 'c10583j', name: 'Elektro Huwyler AG', address: 'Kanalstrasse 10', zip: '6056', city: 'Kägiswil', email: 'info@elektro-huwyler.ch', location: 'Kägiswil', region: 'obwalden', slug: 'elektro-huwyler-ag' },
    { id: 'c10583k', name: 'Elektro Illi AG', address: 'Seewag 2', zip: '6130', city: 'Willisau', email: 'info@elektro-illi.ch', location: 'Willisau', region: 'willisau', slug: 'elektro-illi-ag' },
    { id: 'c10583l', name: 'Elektro Imholz AG', address: 'Militärstrasse 12', zip: '6467', city: 'Schattdorf', email: 'info@elektro-imholz.ch', location: 'Schattdorf', region: 'uri', slug: 'elektro-imholz-ag' },
    { id: 'c10583m', name: 'Elektro Kaiser AG', address: 'Dorfstrasse 10', zip: '6072', city: 'Sachseln', email: 'info@elektro-kaiser.ch', location: 'Sachseln', region: 'obwalden', slug: 'elektro-kaiser-ag' },
    { id: 'c10583n', name: 'Elektro Käch Seetal AG', address: 'Bahnhofstrasse 12', zip: '6275', city: 'Ballwil', email: 'elektro@kaech-seetal.ch', location: 'Ballwil', region: 'seetal', slug: 'elektro-kaech-seetal-ag' },
    { id: 'c10583o', name: 'Elektro Kessler GmbH', address: 'Grundstrasse 26', zip: '6430', city: 'Schwyz', email: 'info@stromer-schwyz.ch', location: 'Schwyz', region: 'schwyz', slug: 'elektro-kessler-gmbh' },
    { id: 'c10583p', name: 'elektro kiser ag', address: 'Waldeggweg 1', zip: '6016', city: 'Hellbühl', email: 'info@elektro-kiser.ch', location: 'Hellbühl', region: 'sursee', slug: 'elektro-kiser-ag' },
    { id: 'c10583q', name: 'Elektro Koch Schötz AG', address: 'Luzernerstrasse 59', zip: '6247', city: 'Schötz', email: 'koch.ag@bluewin.ch', location: 'Schötz', region: 'willisau', slug: 'elektro-koch-schoetz-ag' },
    { id: 'c10602a', name: 'Elektro-Kuster AG', address: 'Wasserfallstrasse 60', zip: '6390', city: 'Engelberg', email: 'info@elektro-kuster-ag.ch', location: 'Engelberg', region: 'obwalden', slug: 'elektro-kuster-ag' },
    { id: 'c10602b', name: 'Elektro Märk AG', address: 'Würzenbachstrasse 24', zip: '6006', city: 'Luzern', email: 'info@elektromaerk.ch', location: 'Luzern', region: 'luzern', slug: 'elektro-maerk-ag' },
    { id: 'c10602c', name: 'Elektro Markus Bösch AG', address: 'Buochserstrasse 16', zip: '6373', city: 'Ennetbürgen', email: 'info@embag.net', location: 'Ennetbürgen', region: 'nidwalden', slug: 'elektro-markus-boesch-ag' },
    { id: 'c10602d', name: 'Elektro Markus Odermatt GmbH', address: 'Herdern 8', zip: '6373', city: 'Ennetbürgen', email: 'info@elektroodermatt.ch', location: 'Ennetbürgen', region: 'nidwalden', slug: 'elektro-markus-odermatt-gmbh' },
    { id: 'c10602e', name: 'Elektro Müller Willisau AG', address: 'Rossgassmoos 6', zip: '6130', city: 'Willisau', email: 'info@em-willisau.ch', location: 'Willisau', region: 'willisau', slug: 'elektro-mueller-willisau-ag' },
    { id: 'c10602f', name: 'Elektro Nauer AG', address: 'Umfahrungsstrasse 11', zip: '6467', city: 'Schattdorf', email: 'info@elektronauer.ch', location: 'Schattdorf', region: 'uri', slug: 'elektro-nauer-ag' },
    { id: 'c10602g', name: 'Elektro Nottwil AG', address: 'Kantonsstrasse 29', zip: '6207', city: 'Nottwil', email: 'info@elektro-nottwil.ch', location: 'Nottwil', region: 'sursee', slug: 'elektro-nottwil-ag' },
    { id: 'c10602h', name: 'Elektro Peter Willisau AG', address: 'Hauptgasse 28', zip: '6130', city: 'Willisau', email: 'info@elektropeter.ch', location: 'Willisau', region: 'willisau', slug: 'elektro-peter-willisau-ag' },
    { id: 'c10602i', name: 'Elektro Planzer AG', address: 'Gotthardstrasse 27', zip: '6460', city: 'Altdorf UR', email: 'info@elektroplanzer.ch', location: 'Altdorf UR', region: 'uri', slug: 'elektro-planzer-ag' },
    { id: 'c10602j', name: 'Elektro Reichmuth AG', address: 'Kirchenstrasse 15', zip: '8843', city: 'Oberiberg', email: 'info@elektro-reichmuth.ch', location: 'Oberiberg', region: 'schwyz', slug: 'elektro-reichmuth-ag' },
    { id: 'c10602k', name: 'Elektro Schatt AG', address: 'Schmalzgrubenstrasse 39', zip: '8842', city: 'Unteriberg', email: 'info@elektro-schatt.ch', location: 'Unteriberg', region: 'schwyz', slug: 'elektro-schatt-ag' },
    { id: 'c10602l', name: 'Elektro Schärli AG', address: 'Schwarzenbergstrasse 17', zip: '6102', city: 'Malters', email: 'info@elektro-schaerli.ch', location: 'Malters', region: 'luzern', slug: 'elektro-schaerli-ag' },
    { id: 'c10602m', name: 'Elektro Schmid Sursee AG', address: 'Geuenseestrasse 7', zip: '6210', city: 'Sursee', email: 'elektro@schmid-sursee.ch', location: 'Sursee', region: 'sursee', slug: 'elektro-schmid-sursee-ag' },
    { id: 'c10602n', name: 'Elektro Schuler AG', address: 'Schulhausstrasse 4', zip: '6052', city: 'Hergiswil NW', email: 'elektro.schuler@bluewin.ch', location: 'Hergiswil NW', region: 'nidwalden', slug: 'elektro-schuler-ag' },
    { id: 'c10602o', name: 'Elektro Stirnimann AG', address: 'Grindel 31', zip: '6017', city: 'Ruswil/LU', email: 'info@elsti.ch', location: 'Ruswil/LU', region: 'sursee', slug: 'elektro-stirnimann-ag' },
    { id: 'c10602p', name: 'Elektro Team Eich AG', address: 'Spillgässli 33', zip: '6205', city: 'Eich', email: 'info@elektroteam-eich.ch', location: 'Eich', region: 'sursee', slug: 'elektro-team-eich-ag' },
    { id: 'c10621a', name: 'Elektroplanung Vinzens GmbH', address: 'Dorfstrasse 15', zip: '6442', city: 'Gersau', email: 'mail@ep-vinzens.ch', location: 'Gersau', region: 'schwyz', slug: 'elektroplanung-vinzens-gmbh' },
    { id: 'c10621b', name: 'Elektro Wallimann AG', address: 'Industriestrasse 4', zip: '6055', city: 'Alpnach Dorf', email: 'info@elektro-wallimann.ch', location: 'Alpnach Dorf', region: 'obwalden', slug: 'elektro-wallimann-ag' },
    { id: 'c10621c', name: 'Elektro Waser AG', address: 'Seestrasse 127', zip: '6052', city: 'Hergiswil NW', email: 'admin@elektro-waser.ch', location: 'Hergiswil NW', region: 'nidwalden', slug: 'elektro-waser-ag' },
    { id: 'c10621d', name: 'Elektro Widmer AG', address: 'Traselinge 2', zip: '6024', city: 'Hildisrieden', email: 'info@elektrowidmerag.ch', location: 'Hildisrieden', region: 'sursee', slug: 'elektro-widmer-ag' },
    { id: 'c10621e', name: 'Elektro Wild + Barmettler AG', address: 'Aawasserstrasse 3', zip: '6370', city: 'Oberdorf', email: 'info@wildbarmettler.ch', location: 'Oberdorf', region: 'nidwalden', slug: 'elektro-wild-barmettler-ag' },
    { id: 'c10621f', name: 'Elektro Zemp GmbH', address: 'Mooshof 15', zip: '6166', city: 'Hasle', email: 'maeni.zemp@bluewin.ch', location: 'Hasle', region: 'entlebuch', slug: 'elektro-zemp-gmbh' },
    { id: 'c10621g', name: 'Elektro Zimmerli Reiden AG', address: 'Hauptstrasse 80', zip: '6260', city: 'Reiden', email: 'walter.zimmerli@bluewin.ch', location: 'Reiden', region: 'willisau', slug: 'elektro-zimmerli-reiden-ag' },
    { id: 'c10621h', name: 'ELEKTRO GETZMANN GmbH', address: 'Büntenstrasse 39', zip: '6218', city: 'Ettiswil', email: 'info@elektro-getzmann.ch', location: 'Ettiswil', region: 'willisau', slug: 'elektro-getzmann-gmbh-ettiswil' },
    { id: 'c10621i', name: 'Elektromatik AG', address: 'Hellbühlerstrasse 29', zip: '6017', city: 'Ruswil', email: 'info@elektromatik.ch', location: 'Ruswil', region: 'sursee', slug: 'elektromatik-ag' },
    { id: 'c10621j', name: 'Elektro-Mösch', address: 'Luzernerstrasse 11', zip: '6010', city: 'Kriens', email: 'elektro-moesch@bluewin.ch', location: 'Kriens', region: 'kriens', slug: 'elektro-moesch' },
    { id: 'c10621k', name: 'ELFEMA AG', address: 'Schönbergstrasse 11', zip: '6252', city: 'Dagmersellen', email: 'info@elfema.com', location: 'Dagmersellen', region: 'willisau', slug: 'elfema-ag' },
    { id: 'c10621l', name: 'ELGI-Plan GmbH', address: 'Hauptstrasse 25', zip: '6281', city: 'Hochdorf', email: 'info@elgi-plan.ch', location: 'Hochdorf', region: 'seetal', slug: 'elgi-plan-gmbh' },
    { id: 'c10621m', name: 'Elkon GmbH', address: 'Bahnstrasse 3', zip: '6242', city: 'Wauwil', email: 'elkon-hunkeler@bluewin.ch', location: 'Wauwil', region: 'sursee', slug: 'elkon-gmbh' },
    { id: 'c10621n', name: 'elmaplan AG', address: 'Schöneggstrasse 5', zip: '6048', city: 'Horw', email: 'info@elmaplan.ch', location: 'Horw', region: 'horw', slug: 'elmaplan-ag' },
    { id: 'c10621o', name: 'ELMI GmbH', address: 'Bergstrasse 14', zip: '6242', city: 'Wauwil', email: 'info@elmi-elektro.ch', location: 'Wauwil', region: 'sursee', slug: 'elmi-gmbh' },
    { id: 'c11437a', name: 'ELWAG Elektro Wolhusen AG', address: 'Menznauerstrasse 24', zip: '6110', city: 'Wolhusen', email: 'info@elektrowolhusen.ch', location: 'Wolhusen', region: 'sursee', slug: 'elwag-elektro-wolhusen-ag' },
    { id: 'c11437b', name: 'energieUri', address: 'Herrengasse 1', zip: '6460', city: 'Altdorf/UR', email: 'mail@energieuri.ch', location: 'Altdorf/UR', region: 'uri', slug: 'energieuri' },
    { id: 'c11437c', name: 'Equans Switzerland AG', address: 'Zollhausstrasse 2', zip: '6015', city: 'Luzern', email: 'luzern.ch@equans.com', location: 'Luzern', region: 'luzern', slug: 'equans-switzerland-ag' },
    { id: 'c11437d', name: 'ETB Jost Furrer', address: 'Lindauring 2', zip: '6023', city: 'Rothenburg', email: 'office@etb-rothenburg.ch', location: 'Rothenburg', region: 'emmen', slug: 'etb-jost-furrer' },
    { id: 'c11437e', name: 'Ettlin AG', address: 'Brünigstrasse 18', zip: '6055', city: 'Alpnach Dorf', email: 'info@elektro-ettlin.ch', location: 'Alpnach Dorf', region: 'obwalden', slug: 'ettlin-ag' },
    { id: 'c11437f', name: 'ewl Verkauf AG', address: 'Industriestrasse 6', zip: '6002', city: 'Luzern', email: 'info@ewl-luzern.ch', location: 'Luzern', region: 'luzern', slug: 'ewl-verkauf-ag' },
    { id: 'c11437g', name: 'EWO Gebäudetechnik AG', address: 'Stanserstrasse 8', zip: '6064', city: 'Kerns', email: 'info@ewo-gbt.ch', location: 'Kerns', region: 'obwalden', slug: 'ewo-gebaeudetechnik-ag' },
    { id: 'c11437h', name: 'EWS AG', address: 'Gotthardstrasse 6', zip: '6438', city: 'Ibach', email: 'info@ews.ch', location: 'Ibach', region: 'schwyz', slug: 'ews-ag' },
    { id: 'c10622a', name: 'Frei + Bättig Elektro AG', address: 'Zellgut 7', zip: '6214', city: 'Schenkon', email: 'info@fb-elektro.ch', location: 'Schenkon', region: 'sursee', slug: 'frei-baettig-elektro-ag' },
    { id: 'c10622b', name: 'Frey+Cie Elektro AG', address: 'Süesswinkel 7', zip: '6002', city: 'Luzern', email: 'info@freycie.ch', location: 'Luzern', region: 'luzern', slug: 'frey-cie-elektro-ag' },
    { id: 'c10622c', name: 'Frey+Cie Elektro AG Stans', address: 'Oberstmühle 1', zip: '6370', city: 'Stans', email: 'info@freycie-stans.ch', location: 'Stans', region: 'nidwalden', slug: 'frey-cie-elektro-ag-stans' },
    { id: 'c10622d', name: 'Frey Electric AG', address: 'Kantonsstrasse 39', zip: '6234', city: 'Triengen', email: 'info@freyelectric.ch', location: 'Triengen', region: 'sursee', slug: 'frey-electric-ag' },
    { id: 'c10622e', name: 'Fries Elektro & Papeterie GmbH', address: 'Fischerhof 1', zip: '6234', city: 'Triengen', email: 'elektro@fries-elektro-papeterie.ch', location: 'Triengen', region: 'sursee', slug: 'fries-elektro-papeterie-gmbh' },
    { id: 'c10630a', name: 'Gasser Elektro-Unternehmung AG', address: 'Dammstrasse 10', zip: '6438', city: 'Ibach/SZ', email: 'info@gasser-elektro.ch', location: 'Ibach/SZ', region: 'schwyz', slug: 'gasser-elektro-unternehmung-ag' },
    { id: 'c10630b', name: 'Gebr. Mathis Elektro AG', address: 'Luzernerstrasse 31', zip: '6037', city: 'Root', email: 'info@mathiselektro.ch', location: 'Root', region: 'rontal', slug: 'gebr-mathis-elektro-ag' },
    { id: 'c10630c', name: 'Gemeindewerk Beckenried', address: 'Oeliweg 4', zip: '6375', city: 'Beckenried/NW', email: 'info@gw.beckenried.ch', location: 'Beckenried/NW', region: 'nidwalden', slug: 'gemeindewerk-beckenried' },
    { id: 'c10630d', name: 'Gemeindewerke Arth', address: 'Gotthardstrasse 21', zip: '6415', city: 'Arth', email: 'info@gwa-energie.ch', location: 'Arth', region: 'schwyz', slug: 'gemeindewerke-arth' },
    { id: 'c10630e', name: 'Gemeindewerke Erstfeld', address: 'Gotthardstrasse 101', zip: '6472', city: 'Erstfeld', email: 'info@gemeindewerke-erstfeld.ch', location: 'Erstfeld', region: 'uri', slug: 'gemeindewerke-erstfeld' },
    { id: 'c10630f', name: 'Georg Imbach AG', address: 'Luzernstrasse 18', zip: '6206', city: 'Neuenkirch', email: 'info@elektro-imbach.ch', location: 'Neuenkirch', region: 'sursee', slug: 'georg-imbach-ag' },
    { id: 'c10630g', name: 'GRÜTER KOCH AG', address: 'Steinenstrasse 5', zip: '6004', city: 'Luzern', email: 'info@grueterkoch.ch', location: 'Luzern', region: 'luzern', slug: 'grueter-koch-ag' },
    { id: 'c10631a', name: 'Häller eltec AG', address: 'Luternau 12', zip: '6018', city: 'Buttisholz', email: 'info@haeller-eltec.ch', location: 'Buttisholz', region: 'sursee', slug: 'haeller-eltec-ag' },
    { id: 'c10631b', name: 'Heggli Service AG', address: 'Schongauerstrasse 9b', zip: '6289', city: 'Müswangen', email: 'info@heggliservice.ch', location: 'Müswangen', region: 'seetal', slug: 'heggli-service-ag' },
    { id: 'c10632a', name: 'IK Elektro GmbH', address: 'Houelbachstrasse 3', zip: '6010', city: 'Kriens', email: 'info@ik-elektro.ch', location: 'Kriens', region: 'kriens', slug: 'ik-elektro-gmbh' },
    { id: 'c10632b', name: 'Illi ICT Solutions AG', address: 'Seewag 2', zip: '6130', city: 'Willisau', email: 'info@illi-ict.ch', location: 'Willisau', region: 'willisau', slug: 'illi-ict-solutions-ag' },
    { id: 'c10632c', name: 'Illi Kontrolle AG', address: 'Seewag 2', zip: '6130', city: 'Willisau', email: 'info@kontrolle-illi.ch', location: 'Willisau', region: 'willisau', slug: 'illi-kontrolle-ag' },
    { id: 'c10632d', name: 'Imbach Elektro AG', address: 'Oberstadt 18', zip: '6210', city: 'Sursee', email: 'imbach-elektro@bluewin.ch', location: 'Sursee', region: 'sursee', slug: 'imbach-elektro-ag' },
    { id: 'c10632e', name: 'Imbach ELKO AG', address: 'Industriestrasse 3', zip: '6034', city: 'Inwil', email: 'info@imbach-elko.ch', location: 'Inwil', region: 'rontal', slug: 'imbach-elko-ag' },
    { id: 'c10632f', name: 'Inderbitzin + Kälin AG', address: 'Gewerbestrasse 23', zip: '6438', city: 'Ibach', email: 'info@iks-elektro.ch', location: 'Ibach', region: 'schwyz', slug: 'inderbitzin-kaelin-ag' },
    { id: 'c10632g', name: 'Infra Tech AG', address: 'Rotzwinkel 17', zip: '6370', city: 'Stans', email: 'info@infratech.ch', location: 'Stans', region: 'nidwalden', slug: 'infra-tech-ag' },
    { id: 'c10632h', name: 'Intelitec AG', address: 'Hansmatt 30', zip: '6370', city: 'Stans', email: 'info@intelitec.ch', location: 'Stans', region: 'nidwalden', slug: 'intelitec-ag' },
    { id: 'c10931a', name: 'Jules Häfliger AG', address: 'Denkmalstrasse 2', zip: '6000', city: 'Luzern', email: 'info@jhaefliger.ch', location: 'Luzern', region: 'luzern', slug: 'jules-haefliger-ag' },
    { id: 'c10633a', name: 'Kälin Elektro & Telematik AG', address: 'Meggerstrasse 6', zip: '6043', city: 'Adligenswil', email: 'mail@kaelin-elektro.ch', location: 'Adligenswil', region: 'rontal', slug: 'kaelin-elektro-telematik-ag' },
    { id: 'c10633b', name: 'Kaufmann Elektro AG', address: 'Bergboden 7', zip: '6110', city: 'Wolhusen', email: 'info@kaufmann-elektro.ch', location: 'Wolhusen', region: 'sursee', slug: 'kaufmann-elektro-ag' },
    { id: 'c10633c', name: 'Knüsel AG', address: 'Engelbergstrasse 46', zip: '6370', city: 'Stans/NW', email: 'elektro@knueselstans.ch', location: 'Stans/NW', region: 'nidwalden', slug: 'knuesel-ag' },
    { id: 'c10633d', name: 'Koni Baumgartner Elektro AG', address: 'Kernserstrasse 11', zip: '6372', city: 'Ennetmoos', email: 'mail@ennetmoos.ch', location: 'Ennetmoos', region: 'nidwalden', slug: 'koni-baumgartner-elektro-ag' },
    { id: 'c10634a', name: 'Lüscher + Partner Elektro AG', address: 'Zellgut 9', zip: '6214', city: 'Schenkon', email: 'info@lpe-ag.ch', location: 'Schenkon', region: 'sursee', slug: 'luescher-partner-elektro-ag' },
    { id: 'c10635a', name: 'Maréchaux Elektro AG', address: 'Inseliquai 12', zip: '6005', city: 'Luzern', email: 'info@marechaux.ch', location: 'Luzern', region: 'luzern', slug: 'marechaux-elektro-ag' },
    { id: 'c10635b', name: 'Maréchaux Elektro AG Stans', address: 'Hansmatt 30', zip: '6370', city: 'Stans', email: 'info@marechaux-stans.ch', location: 'Stans', region: 'nidwalden', slug: 'marechaux-elektro-ag-stans' },
    { id: 'c10635c', name: 'Maréchaux Elektro AG Sursee', address: 'Surentalstrasse 10', zip: '6210', city: 'Sursee', email: 'sursee@marechaux.ch', location: 'Sursee', region: 'sursee', slug: 'marechaux-elektro-ag-sursee' },
    { id: 'c10635d', name: 'Müller Elektro Hitzkirch AG', address: 'Seilerstrasse 19', zip: '6285', city: 'Hitzkirch', email: 'info@muellerelektro.ch', location: 'Hitzkirch', region: 'seetal', slug: 'mueller-elektro-hitzkirch-ag' },
    { id: 'c10635e', name: 'Müller Elestan GmbH', address: 'Landsgemeindestrasse 28', zip: '6438', city: 'Ibach', email: 'mueller-elestan@mythen.ch', location: 'Ibach', region: 'schwyz', slug: 'mueller-elestan-gmbh' },
    { id: 'c10636a', name: 'Niederberger Elektro AG', address: 'Rüeggisingerstrasse 152', zip: '6032', city: 'Emmen', email: 'kontakt@niederberger-elektro.ch', location: 'Emmen', region: 'emmen', slug: 'niederberger-elektro-ag' },
    { id: 'c10636b', name: 'Niederberger Elektro + Multimedia GmbH', address: 'Wydenstrasse 12', zip: '6390', city: 'Engelberg', email: 'info@neme.ch', location: 'Engelberg', region: 'obwalden', slug: 'niederberger-elektro-multimedia-gmbh' },
    { id: 'c10637a', name: 'Odermatt & Sicher AG', address: 'Langmattring 42', zip: '6370', city: 'Stans/NW', email: 'info@odermatt-sicher.ch', location: 'Stans/NW', region: 'nidwalden', slug: 'odermatt-sicher-ag' },
    { id: 'c10637b', name: 'Odermatt Pirmin Elektro GmbH', address: 'Haltistrasse 12', zip: '6376', city: 'Emmetten', email: 'info@elektro-odermatt.ch', location: 'Emmetten', region: 'nidwalden', slug: 'odermatt-pirmin-elektro-gmbh' },
    { id: 'c10637c', name: 'OnTecGroup AG', address: 'Sigristhalde 1', zip: '6102', city: 'Malters', email: 'info@ontec.ch', location: 'Malters', region: 'luzern', slug: 'ontecgroup-ag' },
    { id: 'c10638a', name: 'Parcom Systems AG', address: 'Hasliring 1', zip: '6032', city: 'Emmen', email: 'info@parcom.ch', location: 'Emmen', region: 'emmen', slug: 'parcom-systems-ag' },
    { id: 'c10638b', name: 'PROTEC Elektro AG', address: 'Wegmatt 16', zip: '6048', city: 'Horw', email: 'info@protec-elektro.ch', location: 'Horw', region: 'horw', slug: 'protec-elektro-ag' },
    { id: 'c10638c', name: 'PZM Luzern AG', address: 'Ebenauerstrasse 10', zip: '6048', city: 'Horw', email: 'luzern@pzm.ch', location: 'Horw', region: 'horw', slug: 'pzm-luzern-ag' },
    { id: 'c23356a', name: 'Quali Plan AG', address: 'Spinnereistrasse 7', zip: '6220', city: 'Emmenbrücke', email: 'info@qualiplan.ch', location: 'Emmenbrücke', region: 'emmen', slug: 'quali-plan-ag' },
    { id: 'c10639a', name: 'Räber Elektro GmbH', address: 'Buzibachring 3b', zip: '6023', city: 'Rothenburg', email: 'pascal.raeber@raeber-elektro.ch', location: 'Rothenburg', region: 'emmen', slug: 'raeber-elektro-gmbh' },
    { id: 'c10639b', name: 'R. Schriber Elektro AG', address: 'Bankstrasse 12', zip: '6280', city: 'Hochdorf', email: 'elektro.bernina@rschriber.ch', location: 'Hochdorf', region: 'seetal', slug: 'r-schriber-elektro-ag' },
    { id: 'c10639c', name: 'Reichmuth Elektrik AG', address: 'Gewerbestrasse 14', zip: '6438', city: 'Ibach', email: 'info@reichmuth-elektrik.ch', location: 'Ibach', region: 'schwyz', slug: 'reichmuth-elektrik-ag' },
    { id: 'c10639d', name: 'René Bucher AG', address: 'Alte Landstrasse 1', zip: '6174', city: 'Sörenberg', email: 'elektrobucher@bluewin.ch', location: 'Sörenberg', region: 'entlebuch', slug: 'rene-bucher-ag' },
    { id: 'c10639e', name: 'Robert Widmer AG', address: 'Reusseggstrasse 9', zip: '6002', city: 'Luzern', email: 'info@widmer-elektro.ch', location: 'Luzern', region: 'luzern', slug: 'robert-widmer-ag' },
    { id: 'c10639f', name: 'Roman Betschart Elektro', address: 'Reussstrasse 8', zip: '6472', city: 'Erstfeld', email: 'rbelektro21@bluewin.ch', location: 'Erstfeld', region: 'uri', slug: 'roman-betschart-elektro' },
    { id: 'c10639g', name: 'RSK Elektro AG', address: 'Allmendstrasse 4', zip: '6210', city: 'Sursee', email: 'info@rskelektro.ch', location: 'Sursee', region: 'sursee', slug: 'rsk-elektro-ag' },
    { id: 'c10640a', name: 'SABO Automation und Elektro GmbH', address: 'Erlistrasse 6', zip: '6403', city: 'Küssnacht am Rigi', email: 'elektro@sabogmbh.ch', location: 'Küssnacht am Rigi', region: 'schwyz', slug: 'sabo-automation-und-elektro-gmbh' },
    { id: 'c10640b', name: 'Schärli Elektro.com AG', address: 'Grossmatte Ost 26', zip: '6014', city: 'Luzern', email: 'info@schaerlielektro.com', location: 'Luzern', region: 'luzern', slug: 'schaerli-elektro-com-ag' },
    { id: 'c10640c', name: 'Schibli Elektrotechnik AG', address: 'Burgstrasse 28', zip: '6468', city: 'Attinghausen', email: 'uri@schibli.com', location: 'Attinghausen', region: 'uri', slug: 'schibli-elektrotechnik-ag' },
    { id: 'c10640d', name: 'Schmid Electric GmbH', address: 'Grossmatte Ost 26', zip: '6014', city: 'Luzern', email: 'info@schmid-electric.ch', location: 'Luzern', region: 'luzern', slug: 'schmid-electric-gmbh' },
    { id: 'c10640e', name: 'Schnyder Elektro AG Aesch', address: 'Hauptstrasse 14', zip: '6287', city: 'Aesch LU', email: 'info@schnyder-elektroag.ch', location: 'Aesch LU', region: 'seetal', slug: 'schnyder-elektro-ag-aesch' },
    { id: 'c10640f', name: 'Schumacher Elektro AG', address: 'Martinsgasse 1', zip: '6102', city: 'Malters', email: 'mail@seag-malters.ch', location: 'Malters', region: 'luzern', slug: 'schumacher-elektro-ag' },
    { id: 'c10640g', name: 'SEIGA GmbH', address: 'Sonnsite 3', zip: '6235', city: 'Winikon', email: 'info@seiga.ch', location: 'Winikon', region: 'sursee', slug: 'seiga-gmbh' },
    { id: 'c10640h', name: 'smartelectro schweiz ag', address: 'Haselmatte 2c', zip: '6210', city: 'Sursee', email: 'info@smartelectro.ag', location: 'Sursee', region: 'sursee', slug: 'smartelectro-schweiz-ag' },
    { id: 'c10640i', name: 'Smartteam Elektro AG', address: 'Chrummweid 4', zip: '6026', city: 'Rain', email: 'info@smartteam-elektro.ch', location: 'Rain', region: 'sursee', slug: 'smartteam-elektro-ag' },
    { id: 'c10640j', name: 'Solektra AG', address: 'Brambergstrasse 52', zip: '6004', city: 'Luzern', email: 'hallo@solektra.ch', location: 'Luzern', region: 'luzern', slug: 'solektra-ag' },
    { id: 'c10640k', name: 'Sostro AG', address: 'Luzernerstrasse 10', zip: '6284', city: 'Gelfingen', email: 'info@sostro.ch', location: 'Gelfingen', region: 'seetal', slug: 'sostro-ag' },
    { id: 'c10640l', name: 'Steiner Energie AG', address: 'Industriestrasse 1', zip: '6102', city: 'Malters', email: 'info@steiner-energie.ch', location: 'Malters', region: 'luzern', slug: 'steiner-energie-ag' },
    { id: 'c10640m', name: 'Stierli Solar GmbH', address: 'Moosmatten 6', zip: '6287', city: 'Aesch LU', email: 'info@stierlisolar.ch', location: 'Aesch LU', region: 'seetal', slug: 'stierli-solar-gmbh' },
    { id: 'c10640n', name: 'Stromerei AG', address: 'Gewerbezone 82', zip: '6018', city: 'Buttisholz', email: 'info@steiner-energie.ch', location: 'Buttisholz', region: 'sursee', slug: 'stromerei-ag' },
    { id: 'c10640o', name: 'STS Elektro AG', address: 'Ringstrasse 27', zip: '6010', city: 'Kriens', email: 'info@stselektro.ch', location: 'Kriens', region: 'kriens', slug: 'sts-elektro-ag' },
    { id: 'c10640p', name: 'sts e-tech GmbH', address: 'Ringstrasse 27', zip: '6010', city: 'Kriens', email: 'info@stsetech.ch', location: 'Kriens', region: 'kriens', slug: 'sts-e-tech-gmbh' },
    { id: 'c10640q', name: 'Studer Erwin Elektro AG', address: 'Neudorfstrasse 2', zip: '6027', city: 'Römerswil LU', email: 'info@elektro-studer.ch', location: 'Römerswil LU', region: 'seetal', slug: 'studer-erwin-elektro-ag' },
    { id: 'c10640r', name: 'swisspro AG', address: 'Oberfeld 17', zip: '6037', city: 'Root', email: 'root@swisspro.ch', location: 'Root', region: 'rontal', slug: 'swisspro-ag' },
    { id: 'c23355a', name: 'Telestrom AG', address: 'Lehn 19', zip: '6162', city: 'Entlebuch', email: 'telestrom@telestrom.ch', location: 'Entlebuch', region: 'entlebuch', slug: 'telestrom-ag' },
    { id: 'c23355b', name: 'Topelektro GmbH', address: 'Frauholzstrasse 29', zip: '6422', city: 'Steinen', email: 'kontakt@topelektro.org', location: 'Steinen', region: 'schwyz', slug: 'topelektro-gmbh' },
    { id: 'c23355c', name: 'Tophinke Automation & Gebäudetechnik AG', address: 'Ziegeleihof 7', zip: '6280', city: 'Hochdorf', email: 'contact@tophinke.ch', location: 'Hochdorf', region: 'seetal', slug: 'tophinke-automation-gebaeudetechnik-ag' },
    { id: 'c10930a', name: 'ulrich elektrik gmbh', address: 'Chlösterlistrasse 57', zip: '6403', city: 'Küssnacht am Rigi', email: 'info@ulrich-elektrik.ch', location: 'Küssnacht am Rigi', region: 'schwyz', slug: 'ulrich-elektrik-gmbh' },
    { id: 'c10644a', name: 'Weibel + Sommer Elektro Telecom AG', address: 'Stationsstrasse 89', zip: '6023', city: 'Rothenburg', email: 'elektro@weibel-sommer.ch', location: 'Rothenburg', region: 'emmen', slug: 'weibel-sommer-elektro-telecom-ag' },
    { id: 'c10644b', name: 'Widmer Elektro-Telecom AG', address: 'Ronstrasse 5', zip: '6030', city: 'Ebikon', email: 'elektro@widmer-ebikon.ch', location: 'Ebikon', region: 'rontal', slug: 'widmer-elektro-telecom-ag' },
    { id: 'c10644c', name: 'Wild Electric AG', address: 'Arsenalstrasse 21', zip: '6010', city: 'Kriens', email: 'mail@wildelectric.ch', location: 'Kriens', region: 'kriens', slug: 'wild-electric-ag' },
    { id: 'c10645a', name: 'Zeltner AG', address: 'Luzernerstrasse 37', zip: '6403', city: 'Küssnacht am Rigi', email: 'info@zeltnerag.ch', location: 'Küssnacht am Rigi', region: 'schwyz', slug: 'zeltner-ag' },
    { id: 'c10645b', name: 'Zimmermann Engineering AG', address: 'Gewerbestrasse 8', zip: '6330', city: 'Cham', email: 'info@ze-ag.ch', location: 'Cham', region: 'rontal', slug: 'zimmermann-engineering-ag' },
    { id: 'c10645c', name: 'Zust & van Herk Elektro AG', address: 'Fläcke 7', zip: '6215', city: 'Beromünster', email: 'mail@zust-vanherk.ch', location: 'Beromünster', region: 'sursee', slug: 'zust-van-herk-elektro-ag' }
];